# Permalinks
permalink:           pretty
#relative_permalinks: true

gems:
  - jekyll-paginate

# Setup
title:               "Mollaahmadi's blog"
url:                 http://mollaahmadi.com
description:         'Esmaeil Mollaahmadi'
paginate:            10
highlighter:         null

# About/contact
author:
  name:              'Esmaeil Mollaahmadi'
  email:             'mollaahmadi@gmail.com'
  url:               ''
  github:            'https://github.com/mollaahmadi'
  twitter:           'https://twitter.com/mollaahmadi'

# Custom vars
version:             1.1.0

github:
  repo:              https://github.com/mollaahmadi/mollaahmadi.github.io

excerpt_separator:   <!--more-->

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - output
  - Gruntfile.js
  - package.json
  - tasks.py
  - node_modules
  - dist
